### ISSUE TITLE
How to build your Qt binding?

### ISSUE THREAD

**Issue by pwd96m4a** [demoitem/m3swig#2]
https://github.com/modula3/cm3/tree/master/m3-ui/qt

**Comment by demoitem** [comment]
You need to install libqt4-dev since it only builds against qt4 libraries.
I never upgraded it to qt5. If you have qt5 installed you can revert back
to qt5 by installing qt5-default

After you install libqt4-dev you just build m3qtcore and ship
then build m3qtgui and ship and then you can build one of the
tests.

All this is on linux. Have not tried it on Windows.

**Comment by pwd96m4a** [comment]
@demoitem How to specify the Qt include path? It's unable to find <QtCore/QHash>
